#pragma once
#include <string>

// Translation of the messages printed to the user (issue #6).
//
// Messages are written in English and wrapped in _(), which goes through
// GNU gettext when the build has it (CMake option AWE32EMU_NLS, on by
// default where libintl and msgfmt are found - Linux, MSYS2). Without it _()
// returns the English text unchanged, so the MSVC build needs nothing extra.
//
// The catalogue template is po/awe32emu.pot (regenerated by the CMake target
// `pot`), translations are po/<language>.po. Messages that are composed from
// parts use whole format strings (StrFormat), so a translator sees a
// complete sentence.
//
// N_() only marks a string for extraction; it is translated later with _().

#ifdef AWE32EMU_NLS
#include <libintl.h>
#define _(s) gettext(s)
#else
#define _(s) (s)
#endif
#define N_(s) s

namespace I18n
{
    // Selects the locale from the environment (LANG, LC_ALL, LC_MESSAGES)
    // and binds the catalogue. It is looked up in the directory from the
    // variable AWE32EMU_LOCALEDIR, otherwise in `locale/` next to the
    // executable. Does nothing in a build without gettext.
    void Init(const char* argv0);
}

// printf-style formatting into a std::string.
std::string StrFormat(const char* fmt, ...)
#if defined(__GNUC__) || defined(__clang__)
    __attribute__((format(printf, 1, 2)))
#endif
    ;
