/*
 * 86Box    A hypervisor and IBM PC system emulator.
 *
 *          EMU8000 port-write trace.
 *
 *          NOT PART OF UPSTREAM 86Box. Added locally for the AWE32Emu project.
 *
 *          Writes every write the guest makes to the EMU8000 in the same
 *          format AWE32Emu/ref86box consumes:
 *
 *              <frame> <port hex> <value hex>
 *
 *          <frame> counts samples generated by the chip at 44100 Hz, so the
 *          trace is on the same timebase as the one our own player emits and
 *          the two can be diffed directly.
 *
 *          Enable by pointing EMU8K_TRACE at an output file:
 *
 *              set EMU8K_TRACE=C:\out\dosdriver.trace
 *
 *          With the variable unset this costs one predictable branch per
 *          write and nothing else.
 */
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

#include <86box/snd_emu8k_trace.h>

static FILE    *trace_fp      = NULL;
static int      trace_checked = 0;
static uint64_t trace_frames  = 0;

static void
trace_open(void)
{
    const char *path;

    trace_checked = 1;

    path = getenv("EMU8K_TRACE");
    if ((path == NULL) || (path[0] == '\0'))
        return;

    trace_fp = fopen(path, "wb");
    if (trace_fp == NULL)
        return;

    fprintf(trace_fp, "# EMU8000 port write trace, 44100 Hz timebase\n");
    fprintf(trace_fp, "# written by 86Box, guest-driven\n");
    fprintf(trace_fp, "# <frame> <port hex> <value hex>\n");
    fflush(trace_fp);
}

void
emu8k_trace_advance(int samples)
{
    if (!trace_checked)
        trace_open();

    if ((trace_fp != NULL) && (samples > 0))
        trace_frames += (uint64_t) samples;
}

void
emu8k_trace_write(uint16_t addr, uint16_t val)
{
    if (!trace_checked)
        trace_open();

    if (trace_fp == NULL)
        return;

    fprintf(trace_fp, "%llu %03X %04X\n",
            (unsigned long long) trace_frames, addr, val);

    /* The emulator is usually killed rather than shut down cleanly, so a
       buffered tail would be lost. Writes are rare enough that flushing
       every time costs nothing measurable. */
    fflush(trace_fp);
}

void
emu8k_trace_read(uint16_t addr, uint16_t val)
{
    if (!trace_checked)
        trace_open();

    if (trace_fp == NULL)
        return;

    fprintf(trace_fp, "R %llu %03X %04X\n",
            (unsigned long long) trace_frames, addr, val);
    fflush(trace_fp);
}


/* ------------------------------------------------------------------------ *
 * Recording the EMU8000 output to .wav
 *
 * NOT PART OF UPSTREAM 86Box. Added for AWE32Emu.
 *
 * The buffer is taken straight from the end of emu8k_update(), i.e. the
 * output of the chip itself before the card mixer - exactly what our player
 * produces too, so it can be compared regardless of the mixer volume
 * settings.
 *
 * Switched on by an environment variable:
 *
 *     set AWE32_WAV=C:\out\crazy-86box.wav
 *
 * The header is also finished through atexit; if 86Box crashed, a zero
 * length would stay in it, but the data are there and can be repaired.
 * ------------------------------------------------------------------------ */

static FILE    *wav_fp      = NULL;
static int      wav_checked = 0;
static uint64_t wav_frames  = 0;
static uint64_t wav_last_hdr = 0;

static void
wav_put32(FILE *f, uint32_t v)
{
    fputc(v & 0xff, f);
    fputc((v >> 8) & 0xff, f);
    fputc((v >> 16) & 0xff, f);
    fputc((v >> 24) & 0xff, f);
}

static void
wav_put16(FILE *f, uint16_t v)
{
    fputc(v & 0xff, f);
    fputc((v >> 8) & 0xff, f);
}

/* Writes the real data length into the header and returns to the end of
   the file. Called continuously, not only on exit: 86Box is terminated from
   outside during measurements and `atexit` may not run - then zeros would
   stay in the header and the file would look empty although the data are
   in it. Exactly that happened on the first run (68 MB of data, reported as
   0.0 s). */
static void
wav_flush_header(void)
{
    const uint32_t data_bytes = (uint32_t) (wav_frames * 4);
    const long     here       = ftell(wav_fp);

    fseek(wav_fp, 4, SEEK_SET);
    wav_put32(wav_fp, 36 + data_bytes);
    fseek(wav_fp, 40, SEEK_SET);
    wav_put32(wav_fp, data_bytes);
    fseek(wav_fp, here, SEEK_SET);
    fflush(wav_fp);
}

static void
wav_close(void)
{
    if (wav_fp == NULL)
        return;

    wav_flush_header();
    fclose(wav_fp);
    wav_fp = NULL;
}

static void
wav_open(void)
{
    const char *path;

    wav_checked = 1;

    path = getenv("AWE32_WAV");
    if ((path == NULL) || (path[0] == '\0'))
        return;

    wav_fp = fopen(path, "wb");
    if (wav_fp == NULL)
        return;

    fwrite("RIFF", 1, 4, wav_fp);
    wav_put32(wav_fp, 0);                 /* finished in wav_close() */
    fwrite("WAVEfmt ", 1, 8, wav_fp);
    wav_put32(wav_fp, 16);                /* fmt length */
    wav_put16(wav_fp, 1);                 /* PCM */
    wav_put16(wav_fp, 2);                 /* stereo */
    wav_put32(wav_fp, 44100);
    wav_put32(wav_fp, 44100 * 4);         /* bytes per second */
    wav_put16(wav_fp, 4);                 /* block align */
    wav_put16(wav_fp, 16);                /* bits per sample */
    fwrite("data", 1, 4, wav_fp);
    wav_put32(wav_fp, 0);                 /* finished in wav_close() */

    atexit(wav_close);
}

void
emu8k_trace_wav(const int32_t *buf, int samples)
{
    if (!wav_checked)
        wav_open();
    if ((wav_fp == NULL) || (buf == NULL) || (samples <= 0))
        return;

    for (int i = 0; i < samples * 2; i++) {
        int32_t v = buf[i];

        if (v > 32767)
            v = 32767;
        else if (v < -32768)
            v = -32768;
        wav_put16(wav_fp, (uint16_t) (int16_t) v);
    }
    wav_frames += (uint64_t) samples;

    /* about once per second; two fseeks cost nothing */
    if ((wav_frames - wav_last_hdr) >= 44100) {
        wav_last_hdr = wav_frames;
        wav_flush_header();
    }
}
